alter table commands_to_employees
drop constraint fk_commandsToEmployees_commands;
GO
alter table commands_to_employees
drop constraint fk_commandsToEmployees_employees;
GO
alter table commands_to_employees
drop constraint fk_commandsToEmployees_roles;
GO
drop table commands_to_employees;